name: Build

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update System
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y build-essential cmake ninja-build curl wget pkg-config
      - name: Install MinGW
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20240619/llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64.tar.xz
          tar -xf llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64.tar.xz
          echo "MINGW_ROOT=$(realpath llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64/)" >> $GITHUB_ENV
          echo $(realpath llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64/bin) >> $GITHUB_PATH
          echo CC=aarch64-w64-mingw32-clang >> $GITHUB_ENV
          echo CXX=aarch64-w64-mingw32-clang++ >> $GITHUB_ENV
          echo RC=aarch64-w64-mingw32-windres >> $GITHUB_ENV
          echo AR=aarch64-w64-mingw32-ar >> $GITHUB_ENV
      - name: Download All Dependencies
        run: |
           wget http://libsdl.org/release/SDL2-2.30.5.tar.gz
           wget https://patch-diff.githubusercontent.com/raw/libsdl-org/SDL/pull/4306.diff
           wget https://curl.haxx.se/download/curl-8.8.0.tar.gz
           wget https://download.savannah.gnu.org/releases/freetype/freetype-2.13.2.tar.gz
           wget http://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.gz
           wget https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
           wget https://downloads.xiph.org/releases/opus/opusfile-0.12.tar.gz
           wget https://www.sqlite.org/2024/sqlite-autoconf-3460000.tar.gz
           wget https://code.videolan.org/videolan/x264/-/archive/master/x264-master.tar.bz2
           wget https://ffmpeg.org/releases/ffmpeg-7.0.1.tar.gz
           wget https://github.com/warmcat/libwebsockets/archive/v4.3-stable.tar.gz
           wget https://download.sourceforge.net/libpng/libpng-1.6.43.tar.gz
           wget https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz
           mkdir -p deps
           cd deps
           tar xvf ../SDL2-2.30.5.tar.gz
           tar xvf ../curl-8.8.0.tar.gz
           tar xvf ../libogg-1.3.5.tar.gz
           tar xvf ../opus-1.3.1.tar.gz
           tar xvf ../opusfile-0.12.tar.gz
           tar xvf ../freetype-2.13.2.tar.gz
           tar xvf ../sqlite-autoconf-3460000.tar.gz
           tar xvf ../x264-master.tar.bz2
           tar xvf ../ffmpeg-7.0.1.tar.gz
           tar xvf ../v4.3-stable.tar.gz
           tar xvf ../libpng-1.6.43.tar.gz
           tar xvf ../zlib-1.3.1.tar.gz
      


